name: CI — Playwright

on: [push]

jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup env and run commands
        run: |
          chmod +x scripts/bootstrap_env.sh scripts/capture_screenshot.sh scripts/check_title.sh
          ./scripts/bootstrap_env.sh
          ./scripts/capture_screenshot.sh https://example.com example.png
          ./scripts/check_title.sh https://example.com
